name: Run Crawler and Send Alerts

on:
  schedule:
    - cron: '0 * * * *'   # Runs every hour on the hour (UTC)
  workflow_dispatch:       # Allows manual run from GitHub Actions tab

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run crawler and email alerts
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: |
        python crawler_alert.py

    - name: Commit updated CSVs
      run: |
        git config user.name "GitHub Action"
        git config user.email "actions@github.com"
        git add *.csv || true
        git commit -m "Update article snapshot [skip ci]" || echo "No changes to commit"
        git push || echo "No push needed"
